# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ublox
      url-base: git@github.com:u-blox
    - name: mtfurlan
      url-base: git@github.com:mtfurlan

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.3.0
      import: true
    - name: ubxlib
      remote: ublox
      path: ubxlib
      revision: preview_fix_zephyr_spi_cs_rmea
      clone-depth: 1
